/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentId = IDL.Nat;
export const InterventionType = IDL.Variant({
  'other' : IDL.Null,
  'attendanceWarning' : IDL.Null,
  'financialAid' : IDL.Null,
  'facultyMeeting' : IDL.Null,
  'peerTutoring' : IDL.Null,
  'academicCounseling' : IDL.Null,
  'mentalHealthSupport' : IDL.Null,
});
export const AdvisorId = IDL.Principal;
export const InterventionCreate = IDL.Record({
  'studentId' : StudentId,
  'description' : IDL.Text,
  'interventionType' : InterventionType,
  'advisorId' : AdvisorId,
});
export const InterventionId = IDL.Nat;
export const InterventionStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Intervention = IDL.Record({
  'id' : InterventionId,
  'status' : InterventionStatus,
  'studentId' : StudentId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'interventionType' : InterventionType,
  'advisorId' : AdvisorId,
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const AdvisorStats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'criticalStudents' : IDL.Nat,
  'activeInterventions' : IDL.Nat,
  'resolvedInterventions' : IDL.Nat,
  'atRiskStudents' : IDL.Nat,
});
export const RiskDistribution = IDL.Record({
  'low' : IDL.Nat,
  'high' : IDL.Nat,
  'critical' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const TrendPoint = IDL.Record({
  'low' : IDL.Nat,
  'high' : IDL.Nat,
  'periodLabel' : IDL.Text,
  'critical' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const RiskFactor = IDL.Record({
  'weight' : IDL.Float64,
  'value' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const DropoutRisk = IDL.Record({
  'studentId' : StudentId,
  'predictedAt' : Timestamp,
  'factors' : IDL.Vec(RiskFactor),
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Nat,
});
export const AttendanceRecord = IDL.Record({
  'totalClasses' : IDL.Nat,
  'studentId' : StudentId,
  'attended' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const CourseGrade = IDL.Record({
  'grade' : IDL.Float64,
  'courseName' : IDL.Text,
});
export const AcademicPerformance = IDL.Record({
  'gpa' : IDL.Float64,
  'grades' : IDL.Vec(CourseGrade),
  'studentId' : StudentId,
  'semester' : IDL.Text,
});
export const StudentStatus = IDL.Variant({
  'active' : IDL.Null,
  'droppedOut' : IDL.Null,
  'atRisk' : IDL.Null,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'status' : StudentStatus,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
  'enrollmentDate' : Timestamp,
  'program' : IDL.Text,
});
export const EngagementMetric = IDL.Record({
  'studentId' : StudentId,
  'extracurricularsCount' : IDL.Nat,
  'lmsLoginFrequency' : IDL.Nat,
  'officeHoursAttended' : IDL.Nat,
  'libraryVisits' : IDL.Nat,
});
export const StudentDetail = IDL.Record({
  'risk' : IDL.Opt(DropoutRisk),
  'attendance' : IDL.Opt(AttendanceRecord),
  'performance' : IDL.Opt(AcademicPerformance),
  'student' : Student,
  'engagement' : IDL.Opt(EngagementMetric),
});
export const StudentSummary = IDL.Record({
  'id' : StudentId,
  'status' : StudentStatus,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
  'enrollmentDate' : Timestamp,
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Nat,
  'program' : IDL.Text,
});
export const InterventionUpdate = IDL.Record({
  'status' : InterventionStatus,
  'resolvedAt' : IDL.Opt(Timestamp),
});

export const idlService = IDL.Service({
  'createIntervention' : IDL.Func([InterventionCreate], [Intervention], []),
  'getAdvisorStats' : IDL.Func([], [AdvisorStats], ['query']),
  'getInterventions' : IDL.Func([], [IDL.Vec(Intervention)], ['query']),
  'getRiskDistribution' : IDL.Func([], [RiskDistribution], ['query']),
  'getRiskTrend' : IDL.Func([], [IDL.Vec(TrendPoint)], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentDetail)], ['query']),
  'getStudentInterventions' : IDL.Func(
      [StudentId],
      [IDL.Vec(Intervention)],
      ['query'],
    ),
  'getStudents' : IDL.Func([], [IDL.Vec(StudentSummary)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'updateIntervention' : IDL.Func(
      [InterventionId, InterventionUpdate],
      [IDL.Opt(Intervention)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentId = IDL.Nat;
  const InterventionType = IDL.Variant({
    'other' : IDL.Null,
    'attendanceWarning' : IDL.Null,
    'financialAid' : IDL.Null,
    'facultyMeeting' : IDL.Null,
    'peerTutoring' : IDL.Null,
    'academicCounseling' : IDL.Null,
    'mentalHealthSupport' : IDL.Null,
  });
  const AdvisorId = IDL.Principal;
  const InterventionCreate = IDL.Record({
    'studentId' : StudentId,
    'description' : IDL.Text,
    'interventionType' : InterventionType,
    'advisorId' : AdvisorId,
  });
  const InterventionId = IDL.Nat;
  const InterventionStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Intervention = IDL.Record({
    'id' : InterventionId,
    'status' : InterventionStatus,
    'studentId' : StudentId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'interventionType' : InterventionType,
    'advisorId' : AdvisorId,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const AdvisorStats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'criticalStudents' : IDL.Nat,
    'activeInterventions' : IDL.Nat,
    'resolvedInterventions' : IDL.Nat,
    'atRiskStudents' : IDL.Nat,
  });
  const RiskDistribution = IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'critical' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const TrendPoint = IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'periodLabel' : IDL.Text,
    'critical' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const RiskFactor = IDL.Record({
    'weight' : IDL.Float64,
    'value' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DropoutRisk = IDL.Record({
    'studentId' : StudentId,
    'predictedAt' : Timestamp,
    'factors' : IDL.Vec(RiskFactor),
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Nat,
  });
  const AttendanceRecord = IDL.Record({
    'totalClasses' : IDL.Nat,
    'studentId' : StudentId,
    'attended' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const CourseGrade = IDL.Record({
    'grade' : IDL.Float64,
    'courseName' : IDL.Text,
  });
  const AcademicPerformance = IDL.Record({
    'gpa' : IDL.Float64,
    'grades' : IDL.Vec(CourseGrade),
    'studentId' : StudentId,
    'semester' : IDL.Text,
  });
  const StudentStatus = IDL.Variant({
    'active' : IDL.Null,
    'droppedOut' : IDL.Null,
    'atRisk' : IDL.Null,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'status' : StudentStatus,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
    'enrollmentDate' : Timestamp,
    'program' : IDL.Text,
  });
  const EngagementMetric = IDL.Record({
    'studentId' : StudentId,
    'extracurricularsCount' : IDL.Nat,
    'lmsLoginFrequency' : IDL.Nat,
    'officeHoursAttended' : IDL.Nat,
    'libraryVisits' : IDL.Nat,
  });
  const StudentDetail = IDL.Record({
    'risk' : IDL.Opt(DropoutRisk),
    'attendance' : IDL.Opt(AttendanceRecord),
    'performance' : IDL.Opt(AcademicPerformance),
    'student' : Student,
    'engagement' : IDL.Opt(EngagementMetric),
  });
  const StudentSummary = IDL.Record({
    'id' : StudentId,
    'status' : StudentStatus,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
    'enrollmentDate' : Timestamp,
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Nat,
    'program' : IDL.Text,
  });
  const InterventionUpdate = IDL.Record({
    'status' : InterventionStatus,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  
  return IDL.Service({
    'createIntervention' : IDL.Func([InterventionCreate], [Intervention], []),
    'getAdvisorStats' : IDL.Func([], [AdvisorStats], ['query']),
    'getInterventions' : IDL.Func([], [IDL.Vec(Intervention)], ['query']),
    'getRiskDistribution' : IDL.Func([], [RiskDistribution], ['query']),
    'getRiskTrend' : IDL.Func([], [IDL.Vec(TrendPoint)], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentDetail)], ['query']),
    'getStudentInterventions' : IDL.Func(
        [StudentId],
        [IDL.Vec(Intervention)],
        ['query'],
      ),
    'getStudents' : IDL.Func([], [IDL.Vec(StudentSummary)], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'updateIntervention' : IDL.Func(
        [InterventionId, InterventionUpdate],
        [IDL.Opt(Intervention)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };