/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicPerformance {
  'gpa' : number,
  'grades' : Array<CourseGrade>,
  'studentId' : StudentId,
  'semester' : string,
}
export type AdvisorId = Principal;
export interface AdvisorStats {
  'totalStudents' : bigint,
  'criticalStudents' : bigint,
  'activeInterventions' : bigint,
  'resolvedInterventions' : bigint,
  'atRiskStudents' : bigint,
}
export interface AttendanceRecord {
  'totalClasses' : bigint,
  'studentId' : StudentId,
  'attended' : bigint,
  'percentage' : number,
}
export interface CourseGrade { 'grade' : number, 'courseName' : string }
export interface DropoutRisk {
  'studentId' : StudentId,
  'predictedAt' : Timestamp,
  'factors' : Array<RiskFactor>,
  'riskLevel' : RiskLevel,
  'riskScore' : bigint,
}
export interface EngagementMetric {
  'studentId' : StudentId,
  'extracurricularsCount' : bigint,
  'lmsLoginFrequency' : bigint,
  'officeHoursAttended' : bigint,
  'libraryVisits' : bigint,
}
export interface Intervention {
  'id' : InterventionId,
  'status' : InterventionStatus,
  'studentId' : StudentId,
  'createdAt' : Timestamp,
  'description' : string,
  'interventionType' : InterventionType,
  'advisorId' : AdvisorId,
  'resolvedAt' : [] | [Timestamp],
}
export interface InterventionCreate {
  'studentId' : StudentId,
  'description' : string,
  'interventionType' : InterventionType,
  'advisorId' : AdvisorId,
}
export type InterventionId = bigint;
export type InterventionStatus = { 'resolved' : null } |
  { 'active' : null } |
  { 'pending' : null };
export type InterventionType = { 'other' : null } |
  { 'attendanceWarning' : null } |
  { 'financialAid' : null } |
  { 'facultyMeeting' : null } |
  { 'peerTutoring' : null } |
  { 'academicCounseling' : null } |
  { 'mentalHealthSupport' : null };
export interface InterventionUpdate {
  'status' : InterventionStatus,
  'resolvedAt' : [] | [Timestamp],
}
export interface RiskDistribution {
  'low' : bigint,
  'high' : bigint,
  'critical' : bigint,
  'medium' : bigint,
}
export interface RiskFactor {
  'weight' : number,
  'value' : number,
  'name' : string,
  'description' : string,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface Student {
  'id' : StudentId,
  'status' : StudentStatus,
  'name' : string,
  'year' : bigint,
  'email' : string,
  'enrollmentDate' : Timestamp,
  'program' : string,
}
export interface StudentDetail {
  'risk' : [] | [DropoutRisk],
  'attendance' : [] | [AttendanceRecord],
  'performance' : [] | [AcademicPerformance],
  'student' : Student,
  'engagement' : [] | [EngagementMetric],
}
export type StudentId = bigint;
export type StudentStatus = { 'active' : null } |
  { 'droppedOut' : null } |
  { 'atRisk' : null };
export interface StudentSummary {
  'id' : StudentId,
  'status' : StudentStatus,
  'name' : string,
  'year' : bigint,
  'email' : string,
  'enrollmentDate' : Timestamp,
  'riskLevel' : RiskLevel,
  'riskScore' : bigint,
  'program' : string,
}
export type Timestamp = bigint;
export interface TrendPoint {
  'low' : bigint,
  'high' : bigint,
  'periodLabel' : string,
  'critical' : bigint,
  'medium' : bigint,
}
export interface _SERVICE {
  'createIntervention' : ActorMethod<[InterventionCreate], Intervention>,
  'getAdvisorStats' : ActorMethod<[], AdvisorStats>,
  'getInterventions' : ActorMethod<[], Array<Intervention>>,
  'getRiskDistribution' : ActorMethod<[], RiskDistribution>,
  'getRiskTrend' : ActorMethod<[], Array<TrendPoint>>,
  'getStudent' : ActorMethod<[StudentId], [] | [StudentDetail]>,
  'getStudentInterventions' : ActorMethod<[StudentId], Array<Intervention>>,
  'getStudents' : ActorMethod<[], Array<StudentSummary>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateIntervention' : ActorMethod<
    [InterventionId, InterventionUpdate],
    [] | [Intervention]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];