/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Intervention {
    id: InterventionId;
    status: InterventionStatus;
    studentId: StudentId;
    createdAt: Timestamp;
    description: string;
    interventionType: InterventionType;
    advisorId: AdvisorId;
    resolvedAt?: Timestamp;
}
export type Timestamp = bigint;
export interface EngagementMetric {
    studentId: StudentId;
    extracurricularsCount: bigint;
    lmsLoginFrequency: bigint;
    officeHoursAttended: bigint;
    libraryVisits: bigint;
}
export interface InterventionCreate {
    studentId: StudentId;
    description: string;
    interventionType: InterventionType;
    advisorId: AdvisorId;
}
export interface CourseGrade {
    grade: number;
    courseName: string;
}
export interface AttendanceRecord {
    totalClasses: bigint;
    studentId: StudentId;
    attended: bigint;
    percentage: number;
}
export interface AdvisorStats {
    totalStudents: bigint;
    criticalStudents: bigint;
    activeInterventions: bigint;
    resolvedInterventions: bigint;
    atRiskStudents: bigint;
}
export interface AcademicPerformance {
    gpa: number;
    grades: Array<CourseGrade>;
    studentId: StudentId;
    semester: string;
}
export type AdvisorId = Principal;
export interface DropoutRisk {
    studentId: StudentId;
    predictedAt: Timestamp;
    factors: Array<RiskFactor>;
    riskLevel: RiskLevel;
    riskScore: bigint;
}
export type StudentId = bigint;
export interface RiskFactor {
    weight: number;
    value: number;
    name: string;
    description: string;
}
export interface StudentDetail {
    risk?: DropoutRisk;
    attendance?: AttendanceRecord;
    performance?: AcademicPerformance;
    student: Student;
    engagement?: EngagementMetric;
}
export interface InterventionUpdate {
    status: InterventionStatus;
    resolvedAt?: Timestamp;
}
export interface RiskDistribution {
    low: bigint;
    high: bigint;
    critical: bigint;
    medium: bigint;
}
export type InterventionId = bigint;
export interface TrendPoint {
    low: bigint;
    high: bigint;
    periodLabel: string;
    critical: bigint;
    medium: bigint;
}
export interface StudentSummary {
    id: StudentId;
    status: StudentStatus;
    name: string;
    year: bigint;
    email: string;
    enrollmentDate: Timestamp;
    riskLevel: RiskLevel;
    riskScore: bigint;
    program: string;
}
export interface Student {
    id: StudentId;
    status: StudentStatus;
    name: string;
    year: bigint;
    email: string;
    enrollmentDate: Timestamp;
    program: string;
}
export enum InterventionStatus {
    resolved = "resolved",
    active = "active",
    pending = "pending"
}
export enum InterventionType {
    other = "other",
    attendanceWarning = "attendanceWarning",
    financialAid = "financialAid",
    facultyMeeting = "facultyMeeting",
    peerTutoring = "peerTutoring",
    academicCounseling = "academicCounseling",
    mentalHealthSupport = "mentalHealthSupport"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum StudentStatus {
    active = "active",
    droppedOut = "droppedOut",
    atRisk = "atRisk"
}
export interface backendInterface {
    createIntervention(payload: InterventionCreate): Promise<Intervention>;
    getAdvisorStats(): Promise<AdvisorStats>;
    getInterventions(): Promise<Array<Intervention>>;
    getRiskDistribution(): Promise<RiskDistribution>;
    getRiskTrend(): Promise<Array<TrendPoint>>;
    getStudent(id: StudentId): Promise<StudentDetail | null>;
    getStudentInterventions(studentId: StudentId): Promise<Array<Intervention>>;
    getStudents(): Promise<Array<StudentSummary>>;
    seedSampleData(): Promise<void>;
    updateIntervention(id: InterventionId, update: InterventionUpdate): Promise<Intervention | null>;
}
import type { AcademicPerformance as _AcademicPerformance, AdvisorId as _AdvisorId, AttendanceRecord as _AttendanceRecord, DropoutRisk as _DropoutRisk, EngagementMetric as _EngagementMetric, Intervention as _Intervention, InterventionCreate as _InterventionCreate, InterventionId as _InterventionId, InterventionStatus as _InterventionStatus, InterventionType as _InterventionType, InterventionUpdate as _InterventionUpdate, RiskFactor as _RiskFactor, RiskLevel as _RiskLevel, Student as _Student, StudentDetail as _StudentDetail, StudentId as _StudentId, StudentStatus as _StudentStatus, StudentSummary as _StudentSummary, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createIntervention(arg0: InterventionCreate): Promise<Intervention> {
        if (this.processError) {
            try {
                const result = await this.actor.createIntervention(to_candid_InterventionCreate_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Intervention_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIntervention(to_candid_InterventionCreate_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Intervention_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdvisorStats(): Promise<AdvisorStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvisorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvisorStats();
            return result;
        }
    }
    async getInterventions(): Promise<Array<Intervention>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterventions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterventions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskDistribution(): Promise<RiskDistribution> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskDistribution();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskDistribution();
            return result;
        }
    }
    async getRiskTrend(): Promise<Array<TrendPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskTrend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskTrend();
            return result;
        }
    }
    async getStudent(arg0: StudentId): Promise<StudentDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentInterventions(arg0: StudentId): Promise<Array<Intervention>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentInterventions(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentInterventions(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudents(): Promise<Array<StudentSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudents();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudents();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async updateIntervention(arg0: InterventionId, arg1: InterventionUpdate): Promise<Intervention | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIntervention(arg0, to_candid_InterventionUpdate_n31(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIntervention(arg0, to_candid_InterventionUpdate_n31(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DropoutRisk_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DropoutRisk): DropoutRisk {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_InterventionStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterventionStatus): InterventionStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_InterventionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterventionType): InterventionType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Intervention_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Intervention): Intervention {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StudentDetail_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentDetail): StudentDetail {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StudentStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentStatus): StudentStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StudentSummary_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentSummary): StudentSummary {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentDetail]): StudentDetail | null {
    return value.length === 0 ? null : from_candid_StudentDetail_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DropoutRisk]): DropoutRisk | null {
    return value.length === 0 ? null : from_candid_DropoutRisk_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceRecord]): AttendanceRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AcademicPerformance]): AcademicPerformance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EngagementMetric]): EngagementMetric | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Intervention]): Intervention | null {
    return value.length === 0 ? null : from_candid_Intervention_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    risk: [] | [_DropoutRisk];
    attendance: [] | [_AttendanceRecord];
    performance: [] | [_AcademicPerformance];
    student: _Student;
    engagement: [] | [_EngagementMetric];
}): {
    risk?: DropoutRisk;
    attendance?: AttendanceRecord;
    performance?: AcademicPerformance;
    student: Student;
    engagement?: EngagementMetric;
} {
    return {
        risk: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.risk)),
        attendance: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.attendance)),
        performance: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.performance)),
        student: from_candid_Student_n23(_uploadFile, _downloadFile, value.student),
        engagement: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.engagement))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: _StudentId;
    predictedAt: _Timestamp;
    factors: Array<_RiskFactor>;
    riskLevel: _RiskLevel;
    riskScore: bigint;
}): {
    studentId: StudentId;
    predictedAt: Timestamp;
    factors: Array<RiskFactor>;
    riskLevel: RiskLevel;
    riskScore: bigint;
} {
    return {
        studentId: value.studentId,
        predictedAt: value.predictedAt,
        factors: value.factors,
        riskLevel: from_candid_RiskLevel_n19(_uploadFile, _downloadFile, value.riskLevel),
        riskScore: value.riskScore
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    status: _StudentStatus;
    name: string;
    year: bigint;
    email: string;
    enrollmentDate: _Timestamp;
    program: string;
}): {
    id: StudentId;
    status: StudentStatus;
    name: string;
    year: bigint;
    email: string;
    enrollmentDate: Timestamp;
    program: string;
} {
    return {
        id: value.id,
        status: from_candid_StudentStatus_n25(_uploadFile, _downloadFile, value.status),
        name: value.name,
        year: value.year,
        email: value.email,
        enrollmentDate: value.enrollmentDate,
        program: value.program
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    status: _StudentStatus;
    name: string;
    year: bigint;
    email: string;
    enrollmentDate: _Timestamp;
    riskLevel: _RiskLevel;
    riskScore: bigint;
    program: string;
}): {
    id: StudentId;
    status: StudentStatus;
    name: string;
    year: bigint;
    email: string;
    enrollmentDate: Timestamp;
    riskLevel: RiskLevel;
    riskScore: bigint;
    program: string;
} {
    return {
        id: value.id,
        status: from_candid_StudentStatus_n25(_uploadFile, _downloadFile, value.status),
        name: value.name,
        year: value.year,
        email: value.email,
        enrollmentDate: value.enrollmentDate,
        riskLevel: from_candid_RiskLevel_n19(_uploadFile, _downloadFile, value.riskLevel),
        riskScore: value.riskScore,
        program: value.program
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InterventionId;
    status: _InterventionStatus;
    studentId: _StudentId;
    createdAt: _Timestamp;
    description: string;
    interventionType: _InterventionType;
    advisorId: _AdvisorId;
    resolvedAt: [] | [_Timestamp];
}): {
    id: InterventionId;
    status: InterventionStatus;
    studentId: StudentId;
    createdAt: Timestamp;
    description: string;
    interventionType: InterventionType;
    advisorId: AdvisorId;
    resolvedAt?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_InterventionStatus_n7(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        createdAt: value.createdAt,
        description: value.description,
        interventionType: from_candid_InterventionType_n9(_uploadFile, _downloadFile, value.interventionType),
        advisorId: value.advisorId,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    attendanceWarning: null;
} | {
    financialAid: null;
} | {
    facultyMeeting: null;
} | {
    peerTutoring: null;
} | {
    academicCounseling: null;
} | {
    mentalHealthSupport: null;
}): InterventionType {
    return "other" in value ? InterventionType.other : "attendanceWarning" in value ? InterventionType.attendanceWarning : "financialAid" in value ? InterventionType.financialAid : "facultyMeeting" in value ? InterventionType.facultyMeeting : "peerTutoring" in value ? InterventionType.peerTutoring : "academicCounseling" in value ? InterventionType.academicCounseling : "mentalHealthSupport" in value ? InterventionType.mentalHealthSupport : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "critical" in value ? RiskLevel.critical : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    droppedOut: null;
} | {
    atRisk: null;
}): StudentStatus {
    return "active" in value ? StudentStatus.active : "droppedOut" in value ? StudentStatus.droppedOut : "atRisk" in value ? StudentStatus.atRisk : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    active: null;
} | {
    pending: null;
}): InterventionStatus {
    return "resolved" in value ? InterventionStatus.resolved : "active" in value ? InterventionStatus.active : "pending" in value ? InterventionStatus.pending : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Intervention>): Array<Intervention> {
    return value.map((x)=>from_candid_Intervention_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentSummary>): Array<StudentSummary> {
    return value.map((x)=>from_candid_StudentSummary_n29(_uploadFile, _downloadFile, x));
}
function to_candid_InterventionCreate_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterventionCreate): _InterventionCreate {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_InterventionStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterventionStatus): _InterventionStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_InterventionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterventionType): _InterventionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_InterventionUpdate_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterventionUpdate): _InterventionUpdate {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: StudentId;
    description: string;
    interventionType: InterventionType;
    advisorId: AdvisorId;
}): {
    studentId: _StudentId;
    description: string;
    interventionType: _InterventionType;
    advisorId: _AdvisorId;
} {
    return {
        studentId: value.studentId,
        description: value.description,
        interventionType: to_candid_InterventionType_n3(_uploadFile, _downloadFile, value.interventionType),
        advisorId: value.advisorId
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: InterventionStatus;
    resolvedAt?: Timestamp;
}): {
    status: _InterventionStatus;
    resolvedAt: [] | [_Timestamp];
} {
    return {
        status: to_candid_InterventionStatus_n33(_uploadFile, _downloadFile, value.status),
        resolvedAt: value.resolvedAt ? candid_some(value.resolvedAt) : candid_none()
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterventionStatus): {
    resolved: null;
} | {
    active: null;
} | {
    pending: null;
} {
    return value == InterventionStatus.resolved ? {
        resolved: null
    } : value == InterventionStatus.active ? {
        active: null
    } : value == InterventionStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InterventionType): {
    other: null;
} | {
    attendanceWarning: null;
} | {
    financialAid: null;
} | {
    facultyMeeting: null;
} | {
    peerTutoring: null;
} | {
    academicCounseling: null;
} | {
    mentalHealthSupport: null;
} {
    return value == InterventionType.other ? {
        other: null
    } : value == InterventionType.attendanceWarning ? {
        attendanceWarning: null
    } : value == InterventionType.financialAid ? {
        financialAid: null
    } : value == InterventionType.facultyMeeting ? {
        facultyMeeting: null
    } : value == InterventionType.peerTutoring ? {
        peerTutoring: null
    } : value == InterventionType.academicCounseling ? {
        academicCounseling: null
    } : value == InterventionType.mentalHealthSupport ? {
        mentalHealthSupport: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
